version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.15.1
    steps:
    - checkout
    - run:
        name: Code Linting
        command: |
          yarn && yarn lint

  client-test:
    docker:
    - image: circleci/node:8.15.1
    steps:
    - checkout
    - run:
        name: run client tests
        command: |
          cd client && yarn test
  
  server-test:
    docker:
    - image: circleci/node:8.15.1
    steps:
    - checkout
    - run:
        name: run server tests
        command: |
          cd server && yarn test

  deploy-server:
         machine: true
         steps:
          - checkout
          - run:
              name: Install awsebcli package
              command: |
                sudo apt-get -y -qq update
                sudo apt-get install python-pip python-dev build-essential
                sudo pip install awsebcli==3.14.11
                eb --version
          - run:
              name: Deploy server
              command: |
                cd ./server
                bash deploy.sh
          - run:
              name: Removing aws config
              command: |
                rm -rf ~/.aws

workflows:
  version: 2
  pacman-build:
    jobs:
    - build
    - client-test:
        requires:
        - build
    - server-test:
        requires:
        - build
    - deploy-server:
        requires:
        - client-test
        - server-test
        filters:
          branches:
            only:
              - master
              - production
          